# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UCy0-JjkT4sQ5DXmr48VPHZkzXX-MDat
"""

# ============================================
# SAVE APP.PY - GRADIO APP CODE
# ============================================

app_code = '''
import gradio as gr
from voxcpm import VoxCPM
import soundfile as sf
import tempfile
import os

print("🔄 Loading model...")
model = VoxCPM.from_pretrained("openbmb/VoxCPM2", load_denoiser=False)
print("✅ Model loaded!")

def generate_voice(text, audio_file):
    try:
        if audio_file is not None:
            wav = model.generate(
                text=text,
                reference_wav_path=audio_file,
                cfg_value=1.8,
                inference_timesteps=12,
                denoise=True
            )
        else:
            wav = model.generate(
                text=text,
                cfg_value=1.8,
                inference_timesteps=12,
                denoise=True
            )
        temp_path = tempfile.NamedTemporaryFile(delete=False, suffix=".wav").name
        sf.write(temp_path, wav, 48000)
        return temp_path
    except Exception as e:
        return f"Error: {str(e)}"

# Gradio Interface
with gr.Blocks(title="Urdu Voice Cloning", theme=gr.themes.Soft()) as demo:
    gr.Markdown("""
    # 🎙️ Urdu Voice Cloning Studio
    ### 30+ Languages | 48kHz Quality | Free to Use
    """)

    with gr.Row():
        with gr.Column(scale=1):
            text_input = gr.Textbox(
                label="📝 Text",
                placeholder="Urdu, English, Arabic... kisi bhi language mein text likhein...",
                lines=4
            )
            audio_input = gr.Audio(
                label="🎤 Reference Audio (Optional - Voice Cloning)",
                type="filepath"
            )
            generate_btn = gr.Button("🎵 Generate Voice", variant="primary", size="lg")

        with gr.Column(scale=1):
            audio_output = gr.Audio(label="🔊 Generated Audio", type="filepath")
            gr.Markdown("""
            ### 💡 Tips:
            - **Simple TTS:** Sirf text likhein aur Generate karein
            - **Voice Cloning:** Reference audio upload karein + text
            - **Voice Design:** Parentheses mein description likhein
              *(e.g., "(A calm, natural voice) Assalam-o-Alaikum!")*
            """)

    generate_btn.click(generate_voice, [text_input, audio_input], audio_output)

# Public link
demo.launch(share=True, server_name="0.0.0.0")
'''

# Save file
with open('app.py', 'w', encoding='utf-8') as f:
    f.write(app_code)

print("✅ app.py created successfully!")